apis:
  - name: mds-provider
    pathPrefix: /provider
    port: 4000
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
  - name: mds-agency
    pathPrefix: /agency
    port: 4001
    version: latest
    useDB: true
    migration: true
    useCache: true
    useEvents: true
  - name: mds-audit
    pathPrefix: /audit
    port: 4002
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
  - name: mds-policy
    pathPrefix: /policy
    port: 4003
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
  - name: mds-compliance
    pathPrefix: /compliance
    port: 4004
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
  - name: mds-daily
    pathPrefix: /daily
    port: 4005
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
  - name: mds-native
    pathPrefix: /native
    port: 4006
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true
  - name: mds-policy-author
    pathPrefix: /policy-author
    port: 4007
    version: latest
    useDB: true
    migration: false
    useCache: true
    useEvents: true