<<<<<<< Updated upstream:helm/mds/templates/egress.yaml
{{- if (eq .Values.postgresql.internal false) }}
=======
{{- if .Values.postgresql.host }}
>>>>>>> Stashed changes:charts/mds/templates/egress.yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pg-rw-external
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.postgresql.host }}
  ports:
  - number: {{ $.Values.postgresql.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- if .Values.postgresql.hostReader }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pg-ro-external
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.postgresql.hostReader }}
  ports:
  - number: {{ $.Values.postgresql.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- end }}
{{- end }}
<<<<<<< Updated upstream:helm/mds/templates/egress.yaml
{{- if (eq .Values.redis.internal false) }}
=======
{{- if .Values.redis.host }}
>>>>>>> Stashed changes:charts/mds/templates/egress.yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis-external
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.redis.host }}
  ports:
  - number: {{ $.Values.redis.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- end }}
{{- if (eq .Values.fluentbit.enabled true ) }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: fluentbit-output
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.fluentbit.backend.es.host }}
  ports:
  - number: {{ $.Values.fluentbit.backend.es.port }}
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
{{- end }}
