{{- range $api := .Values.apis }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $api.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ $api.name }}
  ports:
<<<<<<< Updated upstream:helm/mds/templates/service.yaml
  -
    name: http-{{ $api.name }}
    port: {{ $api.port }}
=======
  - name: http-{{ $api.name }}
    port: 80
    targetPort: {{ $api.port }}
>>>>>>> Stashed changes:charts/mds/templates/service.yaml
{{- end }}
