{{- if .Values.tls.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: {{ .Values.tls.domain }}
  dnsNames:
  - {{ .Values.tls.domain }}
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - {{ .Values.tls.domain }}
{{- end }}
