{{- if .Values.postgresql.internal }}
{{- else }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pg-rw-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.postgresql.host }}
  ports:
  - number: {{ $.Values.postgresql.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- if .Values.postgresql.hostReader }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pg-ro-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.postgresql.hostReader }}
  ports:
  - number: {{ $.Values.postgresql.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- end }}
{{- end }}
{{- if .Values.redis.internal }}
{{- else }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.redis.host }}
  ports:
  - number: {{ .Values.redis.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- end }}
{{- if .Values.fluentbit.internal }}
{{- else }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: fluentbit-output
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.fluentbit.backend.es.host }}
  ports:
  - number: {{ .Values.fluentbit.backend.es.port }}
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
{{- end }}
