apis:
  - name: mds-provider
    pathPrefix: /provider
    port: 4000
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience:
  - name: mds-agency
    pathPrefix: /agency
    port: 4001
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience:
  - name: mds-audit
    pathPrefix: /audit
    port: 4002
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience:
  - name: mds-policy
    pathPrefix: /policy
    port: 4003
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience:
  - name: mds-compliance
    pathPrefix: /compliance
    port: 4004
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience:
  - name: mds-daily
    pathPrefix: /daily
    port: 4005
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience:
  - name: mds-native
    pathPrefix: /native
    port: 4006
    version: latest
    useDB: true
    useCache: true
    useEvents: true
    jwtAudience:
registry:
useLatestImage: true
tls:
  enabled: false
jwt:
  issuer:
  enabled: false
postgresql:
  internal: true
  host:
  hostReader:
  port: 5432
  existingSecret: pg-pass
  postgresqlUsername: mdsadmin
  postgresqlDatabase: mds
  image:
    repository: postgres
    tag: 10
redis:
  internal: true
  host:
  port: 6379
  usePassword: false
  cluster:
    enabled: false
  master:
    disableCommands: []
  slave:
    disableCommands: []
fluentbit:
  backend:
    type: es
    es:
      host:
      port:
      scheme:
      # Elastic Index Name
      index: kubernetes_cluster
      type: flb_type
      logstash_prefix: kubernetes_cluster
      replace_dots: "On"
      time_key: "@timestamp"
      # Optional username credential for Elastic X-Pack access
      http_user:
      # Password for user defined in HTTP_User
      http_passwd:
      # Optional TLS encryption to ElasticSearch instance
      tls: "on"
      tls_verify: "off"
      # TLS certificate for the Elastic (in PEM format). Use if tls=on and tls_verify=on.
      tls_ca: ""
      # TLS debugging levels = 1-4
      tls_debug: 4
